#grades

INSERT INTO grades (titulo) VALUES
('Grade 2017 ENSW'),
('Grade 2019 ENSW'),
('Grade Cubo ENSW'),
('Grade CD e IA'),
('Grade ENSW EAD'),

#GRADE 2017 - DISCIPLINAS

INSERT INTO disciplinas (codigo, titulo, periodo, carga_horaria, modalidade)
VALUES

    ('ENSW1009', 'Gerência de Requisitos', '2', 67,'PRESENCIAL'),
    ('ENSW1018', 'Análise e Projeto Orientado a Objetos I', '4', 67,'PRESENCIAL'),
    ('ENSW1010', 'Introdução à Computação e Teoria Geral de Sistemas', '2', NULL,'PRESENCIAL'),
    ('ENSW1006', 'Técnicas de Programação I', '1', 67,'PRESENCIAL'),
    ('ENSW1021', 'Gestão de Pessoas', '4', 33,'EAD'),
    ('ENSW1005', 'Projeto Interdisciplinar I', '1°', 67,'PRESENCIAL'),
    ('ENSW1002', 'Laboratório de Computação I', '1', 67,'PRESENCIAL'),
    ('ENSW1007', 'Arquitetura e Organização de Computadores', '2', 67,'PRESENCIAL'),
    ('ENSW1011', 'Linguagem de Programação I', '2', 67,'PRESENCIAL'),
    ('ENSW1003', 'Matemática Discreta', '1', 67,'PRESENCIAL'),
    ('ENSW1016', 'Projeto Interdisciplinar II', '3', 67,'PRESENCIAL'),
    ('ENSW1014', 'Laboratório de Computação II', '3', 67,'PRESENCIAL'),
    ('ENSW1017', 'Técnicas de Programação II', '3', 67,'PRESENCIAL'),
    ('ENSW1008', 'Elementos de Cálculo e Álgebra Linear', '2', 67,'PRESENCIAL'),
    ('ENSW1037', 'Gerenciamento de Projetos@', '7', 67,'EAD'),
    ('ENSW1034', 'Projeto Interdisciplinar III', '6', 67,'PRESENCIAL'),
    ('ENSW1019', 'Banco de Dados I', '4', 67,'PRESENCIAL'),
    ('ENSW1022', 'Linguagem de Programação II', '4', 67,'PRESENCIAL'),
    ('ENSW1023', 'Sistemas Operacionais', '4', 67,'PRESENCIAL'),
    ('ENSW1026', 'Banco de Dados II', '5', 67,'PRESENCIAL'),
    ('ENSW1033', 'Interação Humano Computador', '6', 67,'PRESENCIAL'),
    ('ENSW1015', 'Metodologia de Pesquisa@', '3', 67,'EAD'),
    ('ENSW1040', 'Estágio Supervisionado I', '7', 100,'PRESENCIAL'),
    ('ENSW1041', 'Empreendedorismo@', '8', 67,'EAD'),
    ('ENSW1013', 'Estatística', '3', 67,'PRESENCIAL'),
    ('ENSW1024', 'Análise e Projeto Orientado a Objetos II', '5', 67,'PRESENCIAL'),
    ('ENSW1029', 'Redes de Computadores', '5', 67,'PRESENCIAL'),
    ('ENSW1031', 'Big Data', '6', 67,'PRESENCIAL'),
    ('ENSW1027', 'Inteligência Artificial', '5', 67,'PRESENCIAL'),
    ('ENSW1042', 'Noções de Direito', '8', 67,'EAD'),
    ('ENSW1039', 'Tópicos Especiais em Engenharia de Software', '7', 67,'PRESENCIAL'),
    ('ENSW1001', 'Administração de Sistemas Empresariais@', '1', 67,'EAD'),
    ('ENSW1044', 'Sociologia@', '8', 67,'EAD'),
    ('ENSW1030', 'Trabalho de Conclusão de Curso I', '5', 67,'PRESENCIAL'),
    ('ENSW1036', 'Trabalho de Conclusão de Curso II', '6', 67,'PRESENCIAL'),
    ('ENSW1038', 'Tópicos Avançados em Computação', '7', 67,'PRESENCIAL'),
    ('ENSW1025', 'Arquitetura de Software', '5', 67,'PRESENCIAL'),
    ('ENSW1032', 'Governança em TIC', '6', 67,'PRESENCIAL'),
    ('ENSW1035', 'Teste de Software', '6', 67,'PRESENCIAL'),
    ('ENSW1028', 'Qualidade de Software', '8', 67,'PRESENCIAL'),
    ('ENSW1020', 'NOME INVALIDO', '4', 67,'PRESENCIAL'),
    ('ENSW1045', 'Estágio Supervisionado II', '8', 100,'PRESENCIAL'),
    ('ENSW1004', 'Processo de Desenvolvimento de Software', '1', 67,'PRESENCIAL'),

    #grade 2019

    ('ENSW2001', 'Desenvolvimento de Aplicativos Móveis', NULL, 60,'PRESENCIAL'),
    ('ENSW2002', 'Gerência de Requisitos', NULL, 60),
    ('ENSW2004', 'Introdução à Computação e Teoria Geral de Sistemas', NULL, 30,'PRESENCIAL'),
    ('ENSW2005', 'Lógica de Programação e Algoritmos', NULL, 60,'PRESENCIAL'),
    ('ENSW2003', 'Gestão de Pessoas@', NULL, 30,'EAD'),
    ('ENSW2006', 'Projeto Interdisciplinar I', NULL, 30,'PRESENCIAL'),
    ('ENSW2011', 'Projeto Interdisciplinar II', NULL, 30,'PRESENCIAL'),
    ('ENSW2007', 'Algoritmos e Estruturas de Dados', NULL, 60,'PRESENCIAL'),
    ('ENSW2008', 'Arquitetura e Organização de Computadores', NULL, 60,'PRESENCIAL'),
    ('ENSW2009', 'Linguagem de Programação Orientada a Objetos', NULL, 60,'PRESENCIAL'),
    ('ENSW2010', 'Matemática Discreta', NULL, 60,'PRESENCIAL'),
    ('ENSW2017', 'Projeto Interdisciplinar III', NULL, 30,'PRESENCIAL'),
    ('ENSW2022', 'Projeto Interdisciplinar IV', NULL, 30,'PRESENCIAL'),
    ('ENSW2012', 'Análise e Projeto de Algoritmos', NULL, 60,'PRESENCIAL'),
    ('ENSW2013', 'Análise e Projeto Orientados a Objetos', NULL, 60,'PRESENCIAL'),
    ('ENSW2014', 'Elementos de Cálculo e Álgebra Linear', NULL, 60,'PRESENCIAL'),
    ('ENSW2015', 'Gerenciamento de Projetos', NULL, 60,'PRESENCIAL'),
    ('ENSW2030', 'Projeto Interdisciplinar V', NULL, 30,'PRESENCIAL'),
    ('ENSW2036', 'Projeto Interdisciplinar VI', NULL, 30,'PRESENCIAL'),
    ('ENSW2020', 'Introdução a Banco de Dados', NULL, 60,'PRESENCIAL'),
    ('ENSW2021', 'Paradigmas de Linguagens de Programação', NULL, 60,'PRESENCIAL'),
    ('ENSW2023', 'Sistemas Operacionais', NULL, 60,'PRESENCIAL'),
    ('ENSW2024', 'Banco de Dados Avançado', NULL, 60,'PRESENCIAL'),
    ('ENSW2025', 'Cálculo Numérico', NULL, 60,'PRESENCIAL'),
    ('ENSW2026', 'Desenvolvimento Web', NULL, 60,'PRESENCIAL'),
    ('ENSW2027', 'Interação Humano Computador', NULL, 60,'PRESENCIAL'),
    ('ENSW2028', 'Metodologia de Pesquisa@', NULL, 60,'EAD'),
    ('ENSW2029', 'Projeto e Desenvolvimento de Sistema I', NULL, 30,'PRESENCIAL'),
    ('ENSW2097', 'Estágio Supervisionado I', '5º', 60,'PRESENCIAL'),
    ('ENSW2031', 'Práticas de Extensão I', '5º', 160,'PRESENCIAL'),
    ('ENSW2032', 'Empreendedorismo@', NULL, 60,'EAD'),
    ('ENSW2033', 'Estatística', NULL, 60,'PRESENCIAL'),
    ('ENSW2034', 'Metodologias Ágeis', NULL, 60,'PRESENCIAL'),
    ('ENSW2035', 'Projeto e Desenvolvimento de Sistema II', NULL, 30,'PRESENCIAL'),
    ('ENSW2037', 'Práticas de Extensão II', NULL, 160,'PRESENCIAL'),
    ('ENSW2038', 'Redes de Computadores', NULL, 60,'PRESENCIAL'),
    ('ENSW2040', 'Ciência de Dados e Aprendizagem de Máquina', NULL, 60,'PRESENCIAL'),
    ('ENSW2041', 'Desenvolvimento com DevOps', NULL, 30,'PRESENCIAL'),
    ('ENSW2043', 'Inteligência Artificial', NULL, 60,'PRESENCIAL'),
    ('ENSW2044', 'Noções de Direito e Ética@', NULL, 60,'EAD'),
    ('ENSW2046', 'Tópicos Especiais em Engenharia de Software', NULL, 30,'PRESENCIAL'),
    ('ENSW2047', 'Administração de Sistemas Empresariais@', NULL, 60,'EAD'),
    ('ENSW2048', 'Computação em Nuvem', NULL, 30,'PRESENCIAL'),
    ('ENSW2049', 'Métricas de Software', NULL, 30,'PRESENCIAL'),
    ('ENSW2050', 'Programação de Jogos', NULL, 60,'PRESENCIAL'),
    ('ENSW2052', 'Sociologia@', NULL, 60,'EAD'),
    ('ENSW2045', 'Trabalho de Conclusão de Curso I', NULL, 30,'PRESENCIAL'),
    ('ENSW2053', 'Trabalho de Conclusão de Curso II', NULL, 30,'PRESENCIAL'),
    ('ENSW2054', 'Tópicos Avançados em Computação', NULL, 30,'PRESENCIAL'),
    ('ENSW2018', 'Arquitetura de Software', NULL, 60,'PRESENCIAL'),
    ('ENSW2042', 'Governança em Tecnologia da Informação e Comunicação', NULL, 60,'PRESENCIAL'),
    ('ENSW2039', 'Teste de Software', NULL, 60,'PRESENCIAL'),
    ('ENSW2051', 'Qualidade de Software', NULL, 60,'PRESENCIAL'),
    ('ENSW2019', 'Gerência de Configuração e Controle de Versão', NULL, 30,'PRESENCIAL'),
    ('ENSW2098', 'Estágio Supervisionado II', NULL, 60,'PRESENCIAL'),
    ('ENSW2016', 'Processo de Desenvolvimento de Software', NULL, 60,'PRESENCIAL'),

#grade cubo ensw

INSERT INTO disciplinas (codigo, titulo, carga_horaria, tipo, modalidade)
VALUES
('ENSW1009', 'Gerência de Requisitos', 67, 'Core', 'PRESENCIAL'),
('ENSW1018', 'Análise e Projeto Orientado a Objetos I', 67, 'Core', 'PRESENCIAL'),
('ENSW1010', 'Introdução à Computação e Teoria Geral de Sistemas@', NULL, 'Core', 'EAD'),
('ENSW1006', 'Técnicas de Programação I', 67, 'Core', 'PRESENCIAL'),
('ENSW1021', 'Gestão de Pessoas@', 33, 'Core', 'EAD'),
('ENSW1005', 'Projeto Interdisciplinar I', 67, 'Core', 'PRESENCIAL'),
('ENSW1002', 'Laboratório de Computação I', 67, 'Core', 'PRESENCIAL'),
('ENSW1007', 'Arquitetura e Organização de Computadores', 67, 'Core', 'PRESENCIAL'),
('ENSW1011', 'Linguagem de Programação I', 67, 'Core', 'PRESENCIAL'),
('ENSW1003', 'Matemática Discreta', 67, 'Core', 'PRESENCIAL'),
('ENSW1016', 'Projeto Interdisciplinar II', 67, 'Core', 'PRESENCIAL'),
('ENSW1014', 'Laboratório de Computação II', 67, 'Core', 'PRESENCIAL'),
('ENSW1017', 'Técnicas de Programação II', 67, 'Core', 'PRESENCIAL'),
('ENSW1008', 'Elementos de Cálculo e Álgebra Linear', 67, 'Core', 'PRESENCIAL'),
('ENSW1037', 'Gerenciamento de Projetos@', 67, 'Core', 'EAD'),
('ENSW1034', 'Projeto Interdisciplinar III', 67, 'Core', 'PRESENCIAL'),
('ENSW1019', 'Banco de Dados I', 67, 'Core', 'PRESENCIAL'),
('ENSW1022', 'Linguagem de Programação II', 67, 'Core', 'PRESENCIAL'),
('ENSW1023', 'Sistemas Operacionais', 67, 'Core', 'PRESENCIAL'),
('ENSW1026', 'Banco de Dados II', 67, 'Core', 'PRESENCIAL'),
('ENSW1033', 'Interação Humano Computador', 67, 'Core', 'PRESENCIAL'),
('ENSW1015', 'Metodologia de Pesquisa@', 67, 'Core', 'EAD'),
('ENSW1040', 'Estágio Supervisionado I', 100, 'Core', 'PRESENCIAL'),
('ENSW1041', 'Empreendedorismo@', 67, 'Core', 'EAD'),
('ENSW1013', 'Estatística', 67, 'Core', 'PRESENCIAL'),
('ENSW1024', 'Análise e Projeto Orientado a Objetos II', 67, 'Core', 'PRESENCIAL'),
('ENSW1029', 'Redes de Computadores', 67, 'Core', 'PRESENCIAL'),
('ENSW1031', 'Big Data', 67, 'Core', 'PRESENCIAL'),
('ENSW1027', 'Inteligência Artificial', 67, 'Core', 'PRESENCIAL'),
('ENSW1042', 'Noções de Direito@', 67, 'Core', 'EAD'),
('ENSW1039', 'Tópicos Especiais em Engenharia de Software', 67, 'Core', 'PRESENCIAL'),
('ENSW1001', 'Administração de Sistemas Empresariais@', 67, 'Core', 'EAD'),
('ENSW1044', 'Sociologia@', 67, 'Core', 'EAD'),
('ENSW1030', 'Trabalho de Conclusão de Curso I', 67, 'Core', 'PRESENCIAL'),
('ENSW1036', 'Trabalho de Conclusão de Curso II', 67, 'Core', 'PRESENCIAL'),
('ENSW1038', 'Tópicos Avançados em Computação', 67, 'Core', 'PRESENCIAL'),
('ENSW1025', 'Arquitetura de Software', 67, 'Core', 'PRESENCIAL'),
('ENSW1032', 'Governança em TIC', 67, 'Core', 'PRESENCIAL'),
('ENSW1035', 'Teste de Software', 67, 'Core', 'PRESENCIAL'),
('ENSW1028', 'Qualidade de Software', 67, 'Core', 'PRESENCIAL'),
('ENSW1020', '13', 67, 'Core', 'PRESENCIAL'),
('ENSW1045', 'Estágio Supervisionado II', 100, 'Core', 'PRESENCIAL'),
('ENSW1004', 'Processo de Desenvolvimento de Software', 67, 'Core', 'PRESENCIAL'),
('COAP230027', 'Desenvolvimento de Aplicativos Móveis: Prototipação de aplicações móveis', 15, 'Core', 'PRESENCIAL'),
('COAP230026', 'Desenvolvimento de Aplicativos Móveis: Criação de API Rest básica', 15, 'Core', 'PRESENCIAL'),
('COAP230013', 'Desenvolvimento de Aplicativos Móveis: Criação de API Rest avançada', 15, 'Flex', 'PRESENCIAL'),
('COAP230033', 'Desenvolvimento de Aplicativos Móveis: Criando um APP avançado com sincronismo', 30, 'Flex', 'PRESENCIAL'),
('COAP230034', 'Desenvolvimento de Aplicativos Móveis: Integração de aplicativo com GoogleMaps', 15, 'Flex', 'PRESENCIAL'),
('COAP230029', 'Desenvolvimento Web: Desenvolvimento Web com MVC', 30, 'Core', 'PRESENCIAL'),
('COAP230011', 'Desenvolvimento Web: Prática em desenvolvimentos WEB@', 30, 'Flex', 'EAD'),
('COAP230012', 'Desenvolvimento Web: Segurança no desenvolvimento WEB@', 15, 'Flex', 'EAD'),
('COAP230030', 'Desenvolvimento Web: Front-end', 15, 'Core', 'PRESENCIAL'),
('COAP230031', 'Desenvolvimento Web: Back-end', 15, 'Core', 'PRESENCIAL'),
('COAP230032', 'Desenvolvimento Web: Criação de sites responsivos', 15, 'Flex', 'PRESENCIAL'),
('COAP230028', 'Desenvolvimento Web: Introdução ao HTML, CSS e Javascript', 30, 'Core', 'PRESENCIAL'),
('EGSW221005', 'Gerência de Requisitos: Artefatos de Software', 15, 'Core', 'PRESENCIAL'),
('EGSW221001', 'Gerência de Requisitos: Introdução a Engenharia de Software', 15, 'Core', 'PRESENCIAL'),
('EGSW221006', 'Gerência de Requisitos: Processo e Desenvolvimento de Software@', 15, 'Flex', 'EAD'),
('EGSW221003', 'Gerência de Requisitos: Modelagem de Processo de Negócios', 15, 'Core', 'PRESENCIAL'),
('EGSW230028', 'Arquitetura de Software: Estilos arquiteturais', 30, 'Core', 'PRESENCIAL'),
('FCOM220003', 'Introdução à Computação e Teoria Geral de Sistemas: Introdução à Computação@', 15, 'Core', 'EAD'),
('FCOM221002', 'Introdução à Computação e Teoria Geral de Sistemas: Hierarquia de Sistemas@', 15, 'Core', 'EAD'),
('ALLP221001', 'Lógica de Programação e Algoritmos: Introdução a lógica de programação', 15, 'Core', 'PRESENCIAL'),
('ALLP221002', 'Lógica de Programação e Algoritmos: Estruturas de decisão e repetição', 15, 'Core', 'PRESENCIAL'),
('ALLP221003', 'Lógica de Programação e Algoritmos: Estrutura de dados estáticas', 15, 'Core', 'PRESENCIAL'),
('ALLP221004', 'Lógica de Programação e Algoritmos: Sub-rotinas', 15, 'Core', 'PRESENCIAL'),
('COAP221003', 'Programação para robótica Móvel: Introdução à robótica', 30, 'Flex', 'PRESENCIAL'),
('COAP221008', 'Programação para robótica Móvel: Robótica Aplicada', 30, 'Flex', 'PRESENCIAL'),
('PRIN221001', 'Projeto Interdisciplinar I: PI I', 15, 'Core', 'PRESENCIAL'),
('PRIN221002', 'Projeto Interdisciplinar I: PI II', 15, 'Core', 'PRESENCIAL'),
('PRIN221003', 'Projeto Interdisciplinar II: PI III', 15, 'Core', 'PRESENCIAL'),
('PRIN221004', 'Projeto Interdisciplinar II: PI IV', 15, 'Core', 'PRESENCIAL'),
('ALLP221006', 'Algoritmos e Estrutura de Dados: Introdução a estrutura de dados', 30, 'Core', 'PRESENCIAL'),
('ALLP221008', 'Algoritmos e Estrutura de Dados: Árvores', 30, 'Core', 'PRESENCIAL'),
('FCOM221003', 'Arquitetura e Organização de Computadores: Organização de Sistemas de Computadores', 30, 'Core', 'PRESENCIAL'),
('FCOM221004', 'Arquitetura e Organização de Computadores: Nível Lógico Digital e Arquitetura do conjunto de instruções', 30, 'Core', 'PRESENCIAL'),
('ALLP230012', 'Linguagem de Programação Orientada a Objetos: Introdução a linguagem de programação orientada a objetos', 30, 'Core', 'PRESENCIAL'),
('ALLP230008', 'Linguagem de Programação Orientada a Objetos: Programação orientada a objetos', 30, 'Core', 'PRESENCIAL'),
('MATE221001', 'Matemática Discreta: Lógica matemática', 30, 'Core', 'PRESENCIAL'),
('MATE221002', 'Matemática Discreta: Sentenças abertas e Quantificadores', 15, 'Core', 'PRESENCIAL'),
('MATE230018', 'Matemática Discreta: Relações e Indução Matemática', 15, 'Core', 'PRESENCIAL'),
('PRIN220001', 'Projeto Interdisciplinar III: PI V', 15, 'Core', 'PRESENCIAL'),
('PRIN220003', 'Projeto Interdisciplinar III: PI VI', 15, 'Core', 'PRESENCIAL'),
('PRIN220010', 'Projeto Interdisciplinar IV: PI VII', 15, 'Core', 'PRESENCIAL'),
('PRIN220004', 'Projeto Interdisciplinar IV: PI VIII', 15, 'Core', 'PRESENCIAL'),
('ALLP230011', 'Análise e Projeto de Algoritmos: Introdução ao Teste de Software', 15, 'Core', 'PRESENCIAL'),
('ALLP230014', 'Análise e Projeto de Algoritmos: Introdução à recursividade', 15, 'Core', 'PRESENCIAL'),
('ALLP230015', 'Análise e Projeto de Algoritmos: Complexidade de algoritmos', 15, 'Core', 'PRESENCIAL'),
('ALLP230007', 'Algoritmos e Estrutura de Dados: Grafos@', 15, 'Core', 'EAD'),
('EGSW230031', 'Análise e Projetos Orientado a Objetos: Introdução a UML com Caso de Uso', 15, 'Core', 'PRESENCIAL'),
('EGSW230005', 'Análise e Projetos Orientado a Objetos: Modelando um software com UML', 30, 'Core', 'PRESENCIAL'),
('EGSW230033', 'Análise e Projetos Orientado a Objetos: Rastreabilidade dos diagramas da UML', 15, 'Core', 'PRESENCIAL'),
('ALLP230012', 'Linguagem de Programação Orientada a Objetos: Introdução a linguagem de programação orientada a objetos', 30, 'Core', 'PRESENCIAL'),
('ALLP230008', 'Linguagem de Programação Orientada a Objetos: Programação orientada a objetos', 30, 'Core', 'PRESENCIAL'),
('MATE230021', 'Elementos de Cálculo e Álgebra Linear: Tópicos de Álgebra Linear', 30, 'Core', 'PRESENCIAL'),
('MATE230020', 'Elementos de Cálculo e Álgebra Linear: Transformações lineares, Autovalor e Autovetor', 15, 'Core', 'PRESENCIAL'),
('MATE230022', 'Elementos de Cálculo e Álgebra Linear: Limites e Continuidade', 15, 'Core', 'PRESENCIAL'),
('MAPC230001', 'Elementos de Cálculo e Álgebra Linear: Matemática para Data Science', 30, 'Flex', 'PRESENCIAL'),
('GNES230002', 'Gerenciamento de Projetos: Fundamentos e Grupos de Processos para Gestão de Projetos@', 30, 'Flex', 'EAD'),
('GNES230003', 'Gerenciamento de Projetos: Gestão de Projetos com PMBOK@', 30, 'Core', 'EAD'),
('GNES230038', 'Gerenciamento de Projetos: Ferramentas para Metodologias Ágeis', 30, 'Core', 'PRESENCIAL'),
('PRIN220006', 'Projeto Interdisciplinar V: PI IX', 15, 'Core', 'PRESENCIAL'),
('PRIN220007', 'Projeto Interdisciplinar V: PI X', 15, 'Core', 'PRESENCIAL'),
('PRIN220008', 'Projeto Interdisciplinar VI: PI XI', 15, 'Core', 'PRESENCIAL'),
('PRIN220009', 'Projeto Interdisciplinar VI: PI XII', 15, 'Core', 'PRESENCIAL'),
('FCOM230001', 'Sistemas Digitais: Circuitos Digitais com a Lógica Combinacional', 30, 'Flex', 'PRESENCIAL'),
('FCOM230002', 'Sistemas Digitais: Circuitos Digitais com a Lógica Sequencial', 30, 'Flex', 'PRESENCIAL'),
('COAP230023', 'Computação Gráfica: Introdução a Computação Gráfica', 30, 'Flex', 'PRESENCIAL'),
('COAP230024', 'Computação Gráfica: Aplicações em Computação Gráfica', 30, 'Flex', 'PRESENCIAL'),
('MATE230002', 'Cálculo Diferencial e Integral: Pré-cálculo', 30, 'Flex', 'PRESENCIAL'),
('MATE230024', 'Cálculo Diferencial e Integral: Derivada, Integral e Aplicações I', 30, 'Flex', 'PRESENCIAL'),
('MATE230025', 'Cálculo Diferencial e Integral: Sequências e Séries', 15, 'Flex', 'PRESENCIAL'),
('MATE230026', 'Cálculo Diferencial e Integral: Derivada, Integral e Aplicações II', 30, 'Flex', 'PRESENCIAL'),
('BDAD230001', 'Introdução a Banco de Dados: Introdução a Banco de Dados', 15, 'Core', 'PRESENCIAL'),
('BDAD230002', 'Introdução a Banco de Dados: Modelagem de banco de dados', 15, 'Core', 'PRESENCIAL'),
('BDAD230003', 'Introdução a Banco de Dados: SQL Básico', 30, 'Core', 'PRESENCIAL'),
('BDAD230009', 'Introdução à Banco de Dados: NoSQL', 15, 'Flex', 'PRESENCIAL'),
('ALLP230005', 'Paradigmas de Linguagens de Programação: Introdução a Paradigmas de Linguagem de Programação', 30, 'Core', 'PRESENCIAL'),
('ALLP230006', 'Paradigmas de Linguagens de Programação: Linguagens Funcionais@', 30, 'Flex', 'EAD'),
('INRC230005', 'Sistemas Operacionais: Introdução à administração de sistemas Linux com RHEL I', 30, 'Flex', 'PRESENCIAL'),
('INRC230006', 'Sistemas Operacionais: Introdução à administração de sistemas Linux com RHEL II', 30, 'Flex', 'PRESENCIAL'),
('FCOM230009', 'Sistemas Operacionais: Princípios de sistemas operacionais@', 15, 'Core', 'EAD'),
('FCOM230010', 'Sistemas Operacionais: Programação multiprocessada e multithreaded', 30, 'Flex', 'PRESENCIAL'),
('FCOM230011', 'Sistemas Operacionais: Sistemas operacionais e memória de computador@', 15, 'Flex', 'EAD'),
('FCOM230012', 'Sistemas Operacionais: Sistemas operacionais e dispositivos', 15, 'Flex', 'PRESENCIAL'),
('BDAD230004', 'Banco de Dados Avançado: Gerenciamento da Transação em Banco de Dados', 15, 'Core', 'PRESENCIAL'),
('BDAD230005', 'Banco de Dados Avançado: Otimização de Consultas e Segurança', 15, 'Core', 'PRESENCIAL'),
('BDAD230006', 'Banco de Dados Avançado: Programação em banco de dados - PL/SQL', 15, 'Flex', 'PRESENCIAL'),
('BDAD230007', 'Banco de Dados Avançado: SQL avançado', 15, 'Core', 'PRESENCIAL'),
('BDAD230008', 'Banco de Dados Avançado: Banco de Dados em Cloud', 15, 'Flex', 'PRESENCIAL'),
('COAP230031', 'Desenvolvimento Web: Back-end', 15, 'Core', 'PRESENCIAL'),
('MATE230013', 'Cálculo numérico: Métodos numéricos para ajuste de curvas', 15, 'Core', 'PRESENCIAL'),
('MAPC230014', 'Cálculo numérico: Sistema em Ponto Flutuante', 15, 'Core', 'PRESENCIAL'),
('MAPC230004', 'Cálculo numérico: Métodos Numéricos Computacionais', 30, 'Core', 'PRESENCIAL'),
('COAP230029', 'Desenvolvimento Web: Desenvolvimento Web com MVC', 30, 'Core', 'PRESENCIAL'),
('COAP230011', 'Desenvolvimento Web: Prática em desenvolvimentos WEB@', 30, 'Flex', 'EAD'),
('COAP230012', 'Desenvolvimento Web: Segurança no desenvolvimento WEB@', 15, 'Flex', 'EAD'),
('COAP230030', 'Desenvolvimento Web: Front-end', 15, 'Core', 'PRESENCIAL'),
('COAP230031', 'Desenvolvimento Web: Back-end', 15, 'Core', 'PRESENCIAL'),
('COAP230032', 'Desenvolvimento Web: Criação de sites responsivos', 15, 'Flex', 'PRESENCIAL'),
('COAP230028', 'Desenvolvimento Web: Introdução ao HTML, CSS e Javascript', 30, 'Core', 'PRESENCIAL'),
('UXUI230001', 'Interação Humano Computador: Princípios do design de sistemas interativos@', 15, 'Core', 'EAD'),
('UXUI230002', 'Interação Humano Computador: Análise contextual e design conceitual@', 15, 'Core', 'EAD'),
('UXUI230003', 'Interação Humano Computador: Design de sistemas interativos', 15, 'Core', 'PRESENCIAL'),
('EGSW230036', 'Interação Humano Computador: Desenvolvimento de Design de Interação', 15, 'Core', 'PRESENCIAL'),
('COAP230030', 'Desenvolvimento Web: Front-end', 15, 'Core', 'PRESENCIAL'),
('COAP230027', 'Desenvolvimento de Aplicativos Móveis: Prototipação de aplicações móveis', 15, 'Core', 'PRESENCIAL'),
('COAP230028', 'Desenvolvimento Web: Introdução ao HTML, CSS e Javascript', 30, 'Core', 'PRESENCIAL'),
('FUNH230001', 'Metodologia de Pesquisa: Estado da Arte e do Conhecimento', 15, 'Flex', 'PRESENCIAL'),
('FUNH230004', 'Metodologia de Pesquisa: Projeto de Pesquisa', 15, 'Flex', 'PRESENCIAL'),
('FUNH230043', 'Metodologia de Pesquisa: Desenvolvimento do Artigo Científico', 15, 'Core', 'PRESENCIAL'),
('FUNH230044', 'Metodologia de Pesquisa: Publicação do Artigo Científico', 15, 'Core', 'PRESENCIAL'),
('ALLP220009', 'Projeto e Desenvolvimento de Sistema I: Análise', 15, 'Core', 'PRESENCIAL'),
('ALLP220010', 'Projeto e Desenvolvimento de Sistema I: Projeto', 15, 'Core', 'PRESENCIAL'),
('EST230168', 'Estágio Supervisionado I: Análise', 30, 'Core', 'PRESENCIAL'),
('EST230169', 'Estágio Supervisionado I: Projeto', 30, 'Core', 'PRESENCIAL'),
('EXTE230011', 'Práticas de Extensão I: Fundamentação e Justificativa', 80, 'Core', 'PRESENCIAL'),
('EXTE230012', 'Práticas de Extensão I: Documentação', 80, 'Core', 'PRESENCIAL'),
('GEIE230001', 'Empreendedorismo: Gestão e Estratégia@', 15, 'Flex', 'EAD'),
('GEIE230002', 'Empreendedorismo: Plano de Negócios@', 15, 'Core', 'EAD'),
('GEIE230003', 'Empreendedorismo: Startups e Plataformas Colaborativas (Crowdfunding)@', 15, 'Flex', 'EAD'),
('GEIE230004', 'Empreendedorismo: Oportunidades empreendedoras e Inovação@', 15, 'Flex', 'EAD'),
('PRIN221001', 'Projeto Interdisciplinar I: PI I', 15, 'Core', 'PRESENCIAL'),
('PRIN221002', 'Projeto Interdisciplinar I: PI II', 15, 'Core', 'PRESENCIAL'),
('PRIN221003', 'Projeto Interdisciplinar II: PI III', 15, 'Core', 'PRESENCIAL'),
('ESDS230001', 'Estatística: Estatística Descritiva', 15, 'Core', 'PRESENCIAL'),
('ESDS230002', 'Estatística: Estatística para Ciência de Dados', 15, 'Core', 'PRESENCIAL'),
('ESDS230003', 'Estatística: Probabilidades e Introdução a Inferência Estatística', 15, 'Core', 'PRESENCIAL'),
('ESDS230004', 'Estatística: Inferência Estatística', 15, 'Core', 'PRESENCIAL'),
('EGSW230024', 'Metodologias Ágeis: Introdução a Metodologias Ágeis@', 15, 'Core', 'EAD'),
('EGSW230025', 'Metodologias Ágeis: Práticas da Modelagem Ágil@', 15, 'Core', 'EAD'),
('EGSW230026', 'Metodologias Ágeis: Desenvolvimento Ágil@', 15, 'Core', 'EAD'),
('GNES230039', 'Metodologias Ágeis: DevOps - Gestão, Conceitos e Cultura', 15, 'Core', 'PRESENCIAL'),
('ALLP220011', 'Projeto e Desenvolvimento de Sistema II: Desenvolvimento', 15, 'Core', 'PRESENCIAL'),
('EXTE230013', 'Práticas de Extensão II: Desenvolvimento', 80, 'Core', 'PRESENCIAL'),
('EXTE230014', 'Práticas de Extensão II: Publicação e Defesa', 80, 'Core', 'PRESENCIAL'),
('INRC230001', 'Redes de Computadores: Introdução à Redes', 15, 'Core', 'PRESENCIAL'),
('INRC230002', 'Redes de Computadores: Acesso à Rede', 15, 'Core', 'PRESENCIAL'),
('INRC230003', 'Redes de Computadores: Endereçamento IP', 15, 'Core', 'PRESENCIAL'),
('INRC230004', 'Redes de Computadores: Camada de Transporte', 15, 'Core', 'PRESENCIAL'),
('ESDS230005', 'Ciência de Dados e Aprendizagem de Máquina: Introdução Data Science', 15, 'Flex', 'PRESENCIAL'),
('MATE230023', 'Ciência de Dados e Aprendizagem de Máquina: Introdução a aplicação de ML em Data Science@', 15, 'Flex', 'EAD'),
('ESDS230001', 'Estatística: Estatística Descritiva', 15, 'Core', 'PRESENCIAL'),
('ESDS230002', 'Estatística: Estatística para Ciência de Dados', 15, 'Core', 'PRESENCIAL'),
('ESDS230003', 'Estatística: Probabilidades e Introdução a Inferência Estatística', 15, 'Core', 'PRESENCIAL'),
('ESDS230004', 'Estatística: Inferência Estatística', 15, 'Core', 'PRESENCIAL'),
('INAR230005', 'Desenvolvimento com DevOps: Controle de Versão e Integração Contínua', 15, 'Core', 'PRESENCIAL'),
('INRC230011', 'Desenvolvimento com DevOps: Gerenciamento de containers', 15, 'Core', 'PRESENCIAL'),
('INAR230001', 'Inteligência Artificial: Agentes inteligentes', 15, 'Core', 'PRESENCIAL'),
('INAR230006', 'Inteligência Artificial: Busca em espaço de estados', 15, 'Core', 'PRESENCIAL'),
('INAR230007', 'Inteligência Artificial: Aprendizado de Máquinas', 30, 'Core', 'PRESENCIAL'),
('INAR230008', 'Inteligência Artificial: Aplicações de Aprendizado de Máquinas', 30, 'Core', 'PRESENCIAL'),
('FUNH230009', 'Noções de Direito e Ética: LGPD - Lei Geral de Proteção de Dados@', 30, 'Core', 'EAD'),
('FUNH230010', 'Noções de Direito e Ética: Elaborando Contratos de Software@', 15, 'Core', 'EAD'),
('FUNH230011', 'Noções de Direito e Ética: Crimes Cibernéticos@', 15, 'Core', 'EAD'),
('EGSW230007', 'Tópicos Especiais em Engenharia de Software: UML Avançada', 30, 'Flex', 'PRESENCIAL'),
('EGSW230033', 'Análise e Projetos Orientado a Objetos: Rastreabilidade dos diagramas da UML', 15, 'Core', 'PRESENCIAL'),
('GNES230004', 'Administração de Sistemas Empresariais: Principios de negócio para Sistemas da Informação@', 15, 'Core', 'EAD'),
('GNES230006', 'Administração de Sistemas Empresariais: Sistemas da Informação com Business Intelligence@', 15, 'Core', 'EAD'),
('GNES230005', 'Administração de Sistemas Empresariais: Disponibilização de Sistemas da Informação para corporações@', 15, 'Flex', 'EAD'),
('GNES230007', 'Administração de Sistemas Empresariais: Sistemas da Informação para organizações@', 15, 'Flex', 'EAD'),
('EGSW230031', 'Análise e Projetos Orientado a Objetos: Introdução a UML com Caso de Uso', 15, 'Core', 'PRESENCIAL'),
('EGSW230005', 'Análise e Projetos Orientado a Objetos: Modelando um software com UML', 30, 'Core', 'PRESENCIAL'),
('GNES230003', 'Gerenciamento de Projetos: Gestão de Projetos com PMBOK@', 30, 'Core', 'EAD'),
('GNES230038', 'Gerenciamento de Projetos: Ferramentas para Metodologias Ágeis', 30, 'Core', 'PRESENCIAL'),
('INRC230007', 'Computação em Nuvem: Introdução a Computação em Nuvem@', 15, 'Core', 'EAD'),
('INRC230008', 'Computação em Nuvem: Modelos de Implantação de Nuvem', 15, 'Flex', 'PRESENCIAL'),
('INRC230009', 'Computação em Nuvem: Prática na Nuvem@', 30, 'Flex', 'EAD'),
('GNES230039', 'Metodologias Ágeis: DevOps - Gestão, Conceitos e Cultura', 15, 'Core', 'PRESENCIAL'),
('INAR230005', 'Desenvolvimento com DevOps: Controle de Versão e Integração Contínua', 15, 'Core', 'PRESENCIAL'),
('INRC230011', 'Desenvolvimento com DevOps: Gerenciamento de containers', 15, 'Core', 'PRESENCIAL'),
('EGSW230035', 'Metricas de Software: Pontos por casos de uso e Pontos por função', 30, 'Core', 'PRESENCIAL'),
('COAP230018', 'Programação de Jogos: Fundamentos de Game Engines@', 30, 'Flex', 'EAD'),
('COAP230019', 'Programação de Jogos: Renderização para Jogos@', 30, 'Flex', 'EAD'),
('COAP230020', 'Programação de Jogos: Inteligência Artificial para Jogos@', 30, 'Flex', 'EAD'),
('COAP230021', 'Programação de Jogos: Jogos digitais com IA competitiva', 15, 'Flex', 'PRESENCIAL'),
('INAR230007', 'Inteligência Artificial: Aprendizado de Máquinas', 30, 'Core', 'PRESENCIAL'),
('INAR230008', 'Inteligência Artificial: Aplicações de Aprendizado de Máquinas', 30, 'Core', 'PRESENCIAL'),
('FUNH230005', 'Sociologia: Introdução ao Conhecimento Sociológico@', 15, 'Core', 'EAD'),
('FUNH230006', 'Sociologia: Sociologia contemporânea@', 15, 'Flex', 'EAD'),
('FUNH230045', 'Sociologia: Sociedade, trabalho e produção', 15, 'Flex', 'PRESENCIAL'),
('PRIN221001', 'Projeto Interdisciplinar I: PI I', 15, 'Core', 'PRESENCIAL'),
('PRIN221002', 'Projeto Interdisciplinar I: PI II', 15, 'Core', 'PRESENCIAL'),
('PRIN221003', 'Projeto Interdisciplinar II: PI III', 15, 'Core', 'PRESENCIAL'),
('TCC230005', 'TCC I: Projeto de Pesquisa', 15, 'Flex', 'PRESENCIAL'),
('TCC230006', 'TCC I: Escrita', 15, 'Flex', 'PRESENCIAL'),
('PRIN221001', 'Projeto Interdisciplinar I: PI I', 15, 'Core', 'PRESENCIAL'),
('PRIN221002', 'Projeto Interdisciplinar I: PI II', 15, 'Core', 'PRESENCIAL'),
('PRIN221003', 'Projeto Interdisciplinar II: PI III', 15, 'Core', 'PRESENCIAL'),
('PRIN221004', 'Projeto Interdisciplinar II: PI IV', 15, 'Core', 'PRESENCIAL'),
('TCC230007', 'TCC II: Desenvolvimento da Pesquisa', 15, 'Flex', 'PRESENCIAL'),
('TCC230008', 'TCC II: Entrega e Defesa', 15, 'Flex', 'PRESENCIAL'),
('PRIN221001', 'Projeto Interdisciplinar I: PI I', 15, 'Core', 'PRESENCIAL'),
('PRIN221002', 'Projeto Interdisciplinar I: PI II', 15, 'Core', 'PRESENCIAL'),
('PRIN221003', 'Projeto Interdisciplinar II: PI III', 15, 'Core', 'PRESENCIAL'),
('PRIN221004', 'Projeto Interdisciplinar II: PI IV', 15, 'Core', 'PRESENCIAL'),
('COAP230001', 'Tópicos Avançados em Computação: Infraestrutura com Docker', 15, 'Flex', 'PRESENCIAL'),
('COAP230002', 'Tópicos Avançados em Computação: Introdução à Internet das Coisas 2.0', 15, 'Flex', 'PRESENCIAL'),
('COAP230003', 'Tópicos Avançados em Computação: Princípios e arquitetura de sistemas distribuídos@', 30, 'Core', 'EAD'),
('COAP230004', 'Tópicos Avançados em Computação: Componentes de sistemas distribuídos@', 30, 'Core', 'EAD'),
('COAP230005', 'Tópicos Avançados em Computação: Manutenção e desempenho de sistemas distribuídos', 30, 'Flex', 'PRESENCIAL'),
('EGSW230028', 'Arquitetura de Software: Estilos arquiteturais', 30, 'Core', 'PRESENCIAL'),
('EGSW230002', 'Arquitetura de Software: Arquitetura e Requisitos@', 30, 'Core', 'EAD'),
('GNES230008', 'Governança em TIC: Introdução a Governança de TI', 15, 'Core', 'PRESENCIAL'),
('GNES230009', 'Governança em TIC: Introdução ao COBIT@', 15, 'Core', 'EAD'),
('GNES230010', 'Governança em TIC: Introdução ao ITIL@', 15, 'Flex', 'EAD'),
('GNES230011', 'Governança em TIC: Introdução ao Archimate@', 30, 'Flex', 'EAD'),
('GNES230012', 'Governança em TIC: Introdução ao TOGAF@', 15, 'Flex', 'EAD'),
('EGSW230014', 'Teste de Software: Introdução a Teste de Software@', 15, 'Core', 'EAD'),
('EGSW230029', 'Teste de Software: Tipos e Fundamentos de Teste de Software', 30, 'Core', 'PRESENCIAL'),
('EGSW230017', 'Teste de Software: Ferramentas de Teste de Software', 15, 'Core', 'PRESENCIAL'),
('EGSW230018', 'Qualidade de Software: Introdução a Qualidade de Software@', 15, 'Core', 'EAD'),
('EGSW230020', 'Qualidade de Software: Principais abordagens de Qualidade de Software@', 15, 'Core', 'EAD'),
('EGSW230021', 'Qualidade de Software: Modelos de Melhoria do Processo de Software@', 30, 'Core', 'EAD'),
('EGSW230012', 'Gerência de Configuração e Controle de Versão: Gerência de Configuração', 15, 'Flex', 'PRESENCIAL'),
('EGSW230013', 'Gerência de Configuração e Controle de Versão: Controle de Versão', 15, 'Flex', 'PRESENCIAL'),
('EGSW230030', 'Gerência de Configuração e Controle de Versão: Introdução ao Controle de Versão', 15, 'Core', 'PRESENCIAL'),
('EGSW230034', 'Gerência de Configuração e Controle de Versão: Entrega contínua', 15, 'Core', 'PRESENCIAL'),
('EST230170', 'Estágio Supervisionado II: Implementação I', 30, 'Core', 'PRESENCIAL'),
('EST230171', 'Estágio Supervisionado II: Implementação II', 30, 'Core', 'PRESENCIAL'),
('EGSW230032', 'Processo e Desenvolvimento de Software: Introdução ao Processo de Desenvolvimento de Software', 15, 'Core', 'PRESENCIAL');
